import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="title" content="Perhisi Ardhian's portfolio website" />
        <meta name="description" content="Portfolio Full-Stack Developer" />
        <meta name="keywords" content="portfolio, full-stack" />
        <meta name="author" content="Perhisi Ardhian" />
        <title>Portfolio | Perhisi Ardhian</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <Script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></Script>
        <link rel="icon" href="icons/img.webp" type="image/x-icon" />
        <link rel="stylesheet" href="./globals.css" />
        <style>

        </style>
      </head>
      <body>{children}</body>
    </html> 
  );
}
